export const counsellers = [
  {
    id: 1,
    name: "Gaitri Sonawane",
    expertise: ["Career Counsellor", "Psychologist", "Group Councellor"],
    experience: "5 years",
    language: "English",
    location: "Mumbai suburban",
  },
  {
    id: 2,
    name: "Mallika Bhagchandani",
    expertise: ["Career Counsellor, Psychologist"],
    experience: "1 years",
    language: "English",
    location: "Mumbai ",
  },
  {
    id: 3,
    name: "Vidya Kumar",
    expertise: ["Career Counsellor", "Psychologist"],
    experience: "6 years",
    language: "English",
    location: "Mumbai district",
  },
  {
    id: 4,
    name: "Satapurni Nag",
    expertise: ["Career Counsellor", "Psychologist", "Group Councellor"],
    experience: "1 years",
    language: "English",
    location: "Bengaluru",
  },
  {
    id: 5,
    name: "Naincy priya",
    expertise: ["Career Counsellor", "Psychologist", "Group Councellor"],
    experience: "5 years",
    language: "English",
    location: "Greater Kailash",
  },
  {
    id: 6,
    name: "Ashish Kishor Rathod",
    expertise: ["Career Counsellor", "Psychologist", "Group Councellor"],
    experience: "5 years",
    language: "English",
    location: "Aurangabad",
  },
  {
    id: 7,
    name: "Neema Nasrin",
    expertise: ["Career Counsellor", "Psychologist"],
    experience: "2 years",
    language: "English",
    location: "Kozhikode",
  },
  {
    id: 8,
    name: "Hanupriya Sharma",
    expertise: ["Career Counsellor", "Psychologist"],
    experience: "6 years",
    language: "English",
    location: "Sirsa",
  },
  {
    id: 9,
    name: "Bareera Sharmin",
    expertise: ["Career Counsellor", "Psychologist", "Group Councellor"],
    experience: "3 years",
    language: "English",
    location: "Bangaluru",
  },
  {
    id: 10,
    name: "Pooja Gupta",
    expertise: ["Career Counsellor", "Psychologist", "Group Counsellor"],
    experience: "5 years",
    language: "English",
    location: "East Delhi",
  },
  {
    id: 11,
    name: "Neema Bajaj",
    expertise: ["Career Counsellor", "Psychologist", "Group Counsellor"],
    experience: "10 months",
    language: "English",
    location: "Dehradun ",
  },
  {
    id: 12,
    name: "Basma Mumtaz",
    expertise: ["Career Counsellor", "Psychologist", "Group Counsellor"],
    experience: "1 years",
    language: "English",
    location: "Palakkad",
  },
  {
    id: 13,
    name: "Paridhi Pareek",
    expertise: ["Career Counsellor", "Psychologist"],
    experience: "Fresher",
    language: "English",
    location: "Ajmer",
  },
];
