export const packages = [
  {
    id: 1,
    title: "Basic Package",
    price: "₹3200 (00% Discount)",
    tax: "Included of taxes (For 18% GST.)",
    suitedFor: [
      "online Assessments",
      "Summary Report",
      "Detailed Analysis of Report",
      "Customized Improvement Tips ",
      "Basic Progress Tackling",
      "Email Support For Queries",
    ],
    totalPay: "₹3200",
  },
  {
    id: 2,
    title: "Advanced Package",
    price: "4000 (20% Discount)",
    tax: "Included of taxes (For 18% GST.)",
    suitedFor: [
      "online Assessments",
      "Summary Report",
      "Detailed Analysis of Report",
      "Customized Improvement Tips ",
      "Basic Progress Tackling",
      "Email Support For Queries",
      "Tailored Action Plan",
      "Virtual Counselling",
    ],
    totalPay: "₹4576",
  },
  {
    id: 3,
    title: "Premium Package",
    price: "5000 (20% Discount)",
    tax: "Included of taxes (For 18% GST.)",
    suitedFor: [
      "online Assessments",
      "Summary Report",
      "Detailed Analysis of Report",
      "Customized Improvement Tips ",
      "Basic Progress Tackling",
      "Email Support For Queries",
      "Tailored Action Plan",
      "Personalized Growth Strategies",
      "In Person Counselling Sessions",
      "Access To Interactive Webinars and Seminar",
    ],
    totalPay: "₹5576",
  },
];
